[package]
name        = "tendermint-p2p"
version     = "0.20.0"
edition     = "2018"
license     = "Apache-2.0"
repository  = "https://github.com/informalsystems/tendermint-rs"
homepage    = "https://tendermint.com"
readme      = "README.md"
keywords    = ["p2p", "tendermint", "cosmos"]
categories  = ["cryptography::cryptocurrencies", "network-programming"]
authors     = [
  "Tony Arcieri <tony@iqlusion.io>",
  "Ismail Khoffi <Ismail.Khoffi@gmail.com>"
]

description = """
    The Tendermint P2P stack in Rust.
    """

[lib]
test = false

[features]
amino = ["prost-amino", "prost-amino-derive"]

[dependencies]
chacha20poly1305 = "0.8"
ed25519-dalek = "1"
eyre = "0.6"
flume = "0.10.7"
hkdf = "0.10.0"
merlin = "2"
prost = "0.8"
rand_core = { version = "0.5", features = ["std"] }
sha2 = "0.9"
subtle = "2"
thiserror = "1"
x25519-dalek = "1.1"
zeroize = "1"

# path dependencies
tendermint = { path = "../tendermint", version = "0.20.0" }
tendermint-proto = { path = "../proto", version = "0.20.0" }

# optional dependencies
prost-amino = { version = "0.6", optional = true }
prost-amino-derive = { version = "0.6", optional = true }
